//
// Generated file, do not edit! Created by opp_msgtool 6.0 from raftMessage.msg.
//

#ifndef __RAFTMESSAGE_M_H
#define __RAFTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class raftMessage;
/**
 * Class generated from <tt>raftMessage.msg:2</tt> by opp_msgtool.
 * <pre>
 * message raftMessage
 * {
 *     int source;
 *     string name;
 * }
 * </pre>
 */
class raftMessage : public ::omnetpp::cMessage
{
  protected:
    int source = 0;
    omnetpp::opp_string name;

  private:
    void copy(const raftMessage& other);

  protected:
    bool operator==(const raftMessage&) = delete;

  public:
    raftMessage(const char *name=nullptr, short kind=0);
    raftMessage(const raftMessage& other);
    virtual ~raftMessage();
    raftMessage& operator=(const raftMessage& other);
    virtual raftMessage *dup() const override {return new raftMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual const char * getName() const;
    virtual void setName(const char * name);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const raftMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, raftMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline raftMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<raftMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RAFTMESSAGE_M_H

